import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Constants from 'expo-constants';

export default function SettingsScreen() {
  const version = Constants.expoConfig?.version ?? '—';
  const publisher =
    (Constants.expoConfig?.extra as Record<string, string> | undefined)?.publisher ??
    'Faith Based Innovations';
  return (
    <SafeAreaView style={styles.root} edges={['bottom']}>
      <ScrollView contentContainerStyle={styles.scroll}>
        <Text style={styles.h1}>About</Text>
        <View style={styles.row}>
          <Text style={styles.label}>App</Text>
          <Text style={styles.value}>Pulse Nexus</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Built by</Text>
          <Text style={styles.value}>{publisher}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Version</Text>
          <Text style={styles.value}>{version}</Text>
        </View>

        <Text style={styles.h2}>How insights work</Text>
        <Text style={styles.p}>
          The Dashboard insights are generated by deterministic rules in this app — no machine
          learning is involved. The exact rules are visible in the source code, so anything the app
          says can be traced back to a specific comparison on your data.
        </Text>

        <Text style={styles.h2}>How the Coach chat works</Text>
        <Text style={styles.p}>
          The Coach tab is a multi-turn chat backed by Google&apos;s Gemini API. Each message is
          sent to Gemini along with a deterministic plain-text summary of your current Pulse Nexus
          metrics, the prior conversation, and the built-in Google Search grounding tool. The
          coach is instructed not to give medical advice. Like any generative AI, it can be wrong —
          verify before relying on its answers, especially for medical, legal, or financial
          questions.
        </Text>

        <Text style={styles.h2}>How the Workouts list works</Text>
        <Text style={styles.p}>
          The Workouts tab pulls workout history in parallel from every connected source — Apple
          Health, WHOOP, Fitbit, and Garmin — normalizes the fields into one shape, and shows them
          newest-first with the source labeled on each card. You can filter by source and by time
          window.
        </Text>

        <Text style={styles.h2}>Privacy</Text>
        <Text style={styles.p}>
          Apple Health data is read on-device. WHOOP, Fitbit, and Garmin data are fetched directly
          from those vendors&apos; servers using OAuth tokens stored in the iOS Keychain — Pulse
          Nexus has no backend of its own. The data that leaves your phone goes to Google&apos;s
          Gemini API only when you use the Coach tab: your message, the prior chat turns, and a
          compact plain-text summary of your current metrics (recovery, HRV, sleep, steps, etc.).
          The Dashboard and Workouts tabs do not send anything off-device.
        </Text>

        <Text style={styles.h2}>Sources we can read</Text>
        <Text style={styles.p}>
          • Apple Health (on-device){'\n'}
          • WHOOP — self-serve developer account at developer.whoop.com{'\n'}
          • Fitbit (incl. new Google-era models and Pixel Watch) — self-serve at dev.fitbit.com{'\n'}
          • Garmin — partner-approval-only at developerportal.garmin.com
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#0b0f14' },
  scroll: { padding: 18 },
  h1: { color: '#f5f7fa', fontSize: 28, fontWeight: '800', marginBottom: 8 },
  h2: { color: '#f5f7fa', fontSize: 20, fontWeight: '700', marginTop: 24, marginBottom: 8 },
  p: { color: '#c2cfdb', fontSize: 15, lineHeight: 22 },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1c242e',
  },
  label: { color: '#8aa0b4', fontSize: 14 },
  value: { color: '#f5f7fa', fontSize: 14, fontWeight: '600' },
});
